name: lastchaos
services:
  mysql:
    image: mariadb:10.4.19
    container_name: lc_mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: America/Sao_Paulo
    volumes:
      - ./DB:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      lastchaos_network:
        ipv4_address: 172.20.0.2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: --event-scheduler=ON --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --lower_case_table_names=1
    restart: unless-stopped

  lc_server:
    build:
      context: .
      dockerfile: Dockerfile.centos
    container_name: lc_server
    stdin_open: true
    tty: true
    volumes:
      - ./ServerRun:/lastchaos/ServerRun
      - ./ServerRun/LogFiles:/lastchaos/LogFiles
    ports:
      - "3001:3001"   # LoginServer
      - "4221:4221"   # GameServer
    networks:
      lastchaos_network:
        ipv4_address: 172.20.0.10
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    command: ["/bin/bash", "-c", "chmod -R 777 /lastchaos && cd /lastchaos/ServerRun && ./startall && tail -f /dev/null"]

networks:
  lastchaos_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16